In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df=pd.read_csv(r"G:\DATA-SCIENCE\tom.csv")
df

number  subject  mark  position
0     125      5.0    80      1122
1     150      4.0    95      2233
2     175      6.0    85      3344
3     200      NaN    90      4455
4     225      5.0    87      5566

In [4]:
df.subject.median()

5.0

In [6]:
df.subject=df.subject.fillna(df.subject.median())
df

number  subject  mark  position
0     125      5.0    80      1122
1     150      4.0    95      2233
2     175      6.0    85      3344
3     200      5.0    90      4455
4     225      5.0    87      5566

In [7]:
new_df=df.drop('position',axis='columns')
new_df

number  subject  mark
0     125      5.0    80
1     150      4.0    95
2     175      6.0    85
3     200      5.0    90
4     225      5.0    87

In [22]:
new_df2=df.position
new_df2

0    1122
1    2233
2    3344
3    4455
4    5566
Name: position, dtype: int64

In [24]:
reg=linear_model.LinearRegression()
reg.fit(new_df,new_df2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
reg.coef_

array([4.44400000e+01, 4.68362563e-13, 1.05670391e-13])

In [26]:
reg.intercept_

-4433.000000000019

In [27]:
reg.predict([[165,5,80]])

array([2899.6])

compare the value

In [18]:
(165*4.44400000e+01)+(5*4.68362563e-13)+(80*1.05670391e-13)-4433.000000000019

2899.5999999999913

In [19]:
reg.predict([[220,7,85]])

array([5343.8])